aws-nuke

- Adds support for deleting ALBs and NLBs
- I noticed that error messages weren't showing, which does make the UX clean, but also can be confusing. I re-enabled all error messages.

Add support for deleting ELB v2. Show error messages.

---

aws/asg_test.go
aws/ebs_test.go
aws/ec2_test.go
aws/elb_test.go
aws/elbv2_test.go

Ensure tests cleanup after themselves

---

commands/cli.go

Sleep for 10 seconds when force flag is set

---

README.md
aws/aws.go
aws/snapshot.go
aws/snapshot_test.go
aws/snapshot_types.go
commands/cli.go

Adds support for nuking snapshots

Snapshot nuking

---

aws/ami_types.go
aws/asg_types.go
aws/aws.go
aws/aws_test.go
aws/ebs_types.go
aws/ec2_types.go
aws/elb_types.go
aws/elbv2_types.go
aws/snapshot_types.go
aws/types.go

Support deleting in batch requests to avoid AWS API request limits

---

.circleci/config.yml

This PR updates the circleci config file to ensure that the switching of AWS creds happens in the same shell so it takes effect

Fix Nuke Sandbox

---

aws/ecs_utils_for_test.go

Frequently the ECS tests fail timing out waiting for the service. I noticed that when this happens, the ECS service actually does show up eventually, so adding a retry loop to see if that makes the tests more stable. So far, ran the build 6 times and it only failed once for a different test (https://circleci.com/gh/gruntwork-io/workflows/cloud-nuke/tree/yori-fix-tests-round-3).

More fixes for test stabilization

---

README.md
aws/aws.go
aws/aws_test.go
commands/cli.go

- Adds --region flag to select specific regions.
- Updated README.md

Adding support to nuke selected region

---

README.md

Adding contribution guidelines as per the discussion in https://github.com/gruntwork-io/cloud-nuke/issues/77

Adding contribution guidelines

---

CONTRIBUTING.md
_docs/rfc/TEMPLATE.md

+ Copy TEMPLATE from Terragrunt's repo

Fix labels from Terragrunt on contributing

---

README.md

Updated readme to add documentation for `--exclude-resource-type`

Adding documentation for --exclude-resource-type

---

README.md

This option is available per discussion on https://github.com/gruntwork-io/cloud-nuke/issues/117

Add homebrew to install instructions on README

---

README.md
aws/aws.go
aws/lambda.go
aws/lambda_test.go
aws/lambda_types.go
aws/lambda_utils_for_test.go
commands/cli.go

This PR implements the feature to delete Lambda Functions based on its "LastModified" date, as proposed in #67.

Add feature to delete Lambda Functions

---

aws/aws.go
aws/transit_gateway.go

Should fix the issue described in #187.

Check if Transit Gateway is available in the given region

---

.circleci/nuke_config.yml

- Adding more buckets to clean up the account
- Remove include all.

Update S3 nuke config for phx-ops

---

aws/iam_test.go

Attempt to fix TestDeleteFullIamUser by adding retries in the assignment of MFA device
Execution result:
Fixes:
#227

#227 Fix TestDeleteFullIamUser

---

aws/aws.go
aws/ecs_cluster.go
aws/ecs_cluster_test.go
aws/s3.go

Raised PR with some cleanup of code:
* getAllEcsClustersOlderThan - usage of existing AWS session
* updated range iterations

Code cleanup

---

README.md
aws/aws.go
aws/dynamodb.go
aws/dynamodb_test.go
config/config.go
config/config_test.go
config/mocks/dynamodb_empty.yaml
config/mocks/dynamodb_empty_filters.yaml
config/mocks/dynamodb_empty_rules.yaml
config/mocks/dynamodb_exclude_names.yaml
config/mocks/dynamodb_filter_names.yaml
config/mocks/dynamodb_include_names.yaml

Add support to filter DynamoDB tables by name in config file.
Test output:
https://gist.github.com/brandonstrohmeyer/5db0fe02483b35c0900f13f2c876b301

Add DynamoDB config file support

---

aws/ec2.go
aws/ec2_test.go
aws/ec2_unit_test.go
aws/mock_ec2_utils_for_test.go

Delete Endpoints as part of VPC nuking

---

README.md
aws/aws.go
aws/elasticache.go
aws/elasticache_test.go
aws/elasticache_types.go
config/config.go
config/config_test.go

Fixes #236 
Open question: do we want to add support for Elasticache to the config file?

Add ability to nuke Elasticache

---

README.md
aws/aws.go
aws/ec2_unit_test.go
aws/ec2_vpc.go
aws/ec2_vpc_test.go
config/config.go
config/config_test.go

VPC config file support

---

aws/aws.go
aws/ec2_vpc.go
aws/ec2_vpc_test.go

Add --older-than support to VPC

---

aws/ecs_cluster_test.go
aws/ecs_utils_for_test.go
aws/eip_test.go

Failing tests fixes, included changes:
* synchronized obtaining of elastic IP request - parallel requests may generate the same id
* added filtration of ECS clusters during listing to avoid cases when are read clusters in removal state
* added retries to confirm ECS cluster running

#299 Failing tests fixes

---

aws/elasticache.go

Fixes a minor typo in `aws/elasticache.go`.

Fix typo in aws/elasticache.go

---

commands/cli.go

Clarify force flag's behavior

---

README.md
aws/aws.go
aws/cloudtrail.go
aws/cloudtrail_test.go
aws/cloudtrail_types.go
config/config.go
config/config_test.go
config/mocks/cloudtrail_empty.yaml
config/mocks/cloudtrail_empty_filters.yaml
config/mocks/cloudtrail_empty_rules.yaml
config/mocks/cloudtrail_exclude_names.yaml
config/mocks/cloudtrail_filter_names.yaml
config/mocks/cloudtrail_include_names.yaml

Fixes #299 .
Implement support for CloudTrail Trails

Support CloudTrail

---

.circleci/config.yml

Fixes whitespace issue in yml file for circleci.
Fixed and issue with circleci config file.

Fix whitespace

---

.github/pull_request_template.md

Update pull request template with check re: exclusions

---

commands/cli.go

Support use of --log-level flag in inspect-aws command

---

aws/iam_group.go
aws/iam_policy.go

Adds support for IAM groups and IAM policies to the new UI framework.
- [ X ] Update the docs.
- [ X ] Run the relevant tests successfully, including pre-commit checks.
- [ X ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ X ] Include release notes. If this PR is backward incompatible, include a migration guide.
- [ X ] Attention Grunts - if this PR adds support for a new resource, ensure the `nuke_sandbox` and `nuke_phxdevops` jobs in `.circleci/config.yml` have been updated with …

CORE-298 Use new UI with IAM groups and IAM policies

---

aws/rds_subnet_group_test.go
config/config_test.go
go.sum

Fixes build error issue with this commit https://github.com/gruntwork-io/cloud-nuke/commit/8938011d72e05f96ea8af9515a745f2058aa869d
Updated [Fix build errors in config_test]

Fix errors in config_test

---

.circleci/config.yml

keep network resources around

---

aws/apigatewayv2_test.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/493
Updated [Fix TestListAPIGatewaysV2 test failures]

Fix TestListAPIGatewaysV2 test failures

---

aws/acm.go
aws/acm_test.go
aws/acm_types.go
aws/aws.go

Updated [Refactor ACM resource type]

Refactor ACM resource type

---

aws/acmpca.go
aws/acmpca_test.go
aws/acmpca_types.go
aws/aws.go
config/config.go

Updated [Refactor ACMPCA  resource type]

Refactor ACMPCA Resource Type

---

aws/apigatewayv2.go
aws/apigatewayv2_test.go
aws/apigatewayv2_types.go
aws/aws.go

Updated [Refactor ApiGatewayV2 resource type]

Refactor ApiGatewayV2 resource type

---

aws/aws.go
aws/dynamodb.go
aws/dynamodb_test.go
aws/dynamodb_types.go

Refactor DynamoDB

---

aws/aws.go
aws/transit_gateway.go
aws/transit_gateway_test.go
aws/transit_gateway_types.go

Updated [Refactor Transit Gateway Resource Types]

Refactor Transit Gateway Resource Types

---

aws/aws.go
aws/ebs.go
aws/ebs_test.go
aws/ebs_types.go
aws/snapshot.go
aws/snapshot_test.go
aws/snapshot_types.go
config/config.go
config/config_test.go

Updated [Refactor EC2 Snapshot & EBS Resource Type]

Refactor EC2 Snapshot & EBS Resource Type

---

aws/aws.go
aws/rds.go
aws/rds_test.go
aws/rds_types.go

Updated [Refactor DBINstnaces Resource Type]

Refactor DBINstnaces Resource Type

---

aws/aws.go
aws/oidc_provider.go
aws/oidc_provider_test.go
aws/oidc_provider_types.go

Updated [Refactor oidc resource type]

Refactor oidc resource type

---

aws/aws.go
aws/opensearch.go
aws/opensearch_test.go
aws/opensearch_types.go
util/time.go

Updated [Refactor OpenSearchDomains resource type]

Refactor OpenSearchDomains resource type

---

aws/aws.go
aws/lambda.go
aws/lambda_test.go
aws/lambda_types.go

Updated [refactor lambda functions]

refactor lambda functions

---

aws/aws.go
aws/launch_config.go
aws/launch_config_test.go
aws/launch_config_types.go

Updated [Refactor launch configuration]

Refactor launch configuration

---

aws/aws.go
aws/launch_template.go
aws/launch_template_test.go
aws/launch_template_types.go

Updated [refactor launch template]

refactor launch template

---

aws/aws.go
aws/macie.go
aws/macie_test.go
aws/macie_types.go

Refactor macie

---

aws/aws.go
aws/nat_gateway.go
aws/nat_gateway_test.go
aws/nat_gateway_types.go

Updated [Refactor nat gateway]

Refactor nat gateway

---

aws/aws.go
aws/iam_policy.go
aws/iam_policy_test.go
aws/iam_policy_types.go

Updated [refactor IAM policies]

refactor IAM policies

---

aws/aws.go
aws/eks_utils_for_test.go
aws/elbv2.go
aws/elbv2_test.go
aws/elbv2_types.go

refactor elbv2

---

aws/aws.go
aws/guardduty.go
aws/guardduty_test.go
aws/guardduty_types.go

refactor guard duty

---

aws/aws.go
aws/elb.go
aws/elb_test.go
aws/elb_types.go

refactor elb

---

aws/rds_subnet_group_test.go

Fixes unit test errors in RDS subnet group resource type.
Updated [Fix unit test errors in RDS subnet group test]

Fix unit test errors in RDS subnet group test

---

aws/aws.go
aws/efs.go
aws/efs_test.go
aws/efs_types.go

refactor EFS

---

aws/aws.go
aws/ec2.go
aws/ec2_dedicated_host.go
aws/ec2_test.go
aws/ec2_vpc.go
aws/ec2_vpc_test.go
aws/ec2_vpc_types.go
aws/eip.go
util/time.go

refactor EC2 VPC

---

aws/aws.go
aws/ecr.go
aws/ecr_test.go
aws/ecr_types.go

Updated [Refactor Eip]
Updated [refactor ECR]

refactor ECR

---

aws/aws.go
aws/elasticache.go
aws/elasticache_test.go
aws/elasticache_types.go

Updated [refactor elastic cache]

refactor elastic cache

---

aws/aws.go
aws/ec2_dedicated_host.go
aws/ec2_dedicated_host_test.go
aws/ec2_dedicated_host_types.go

Updated [Refactor Eip]
Updated [Refactor EC2 Dedicated host]

Refactor EC2 Dedicated host

---

aws/access_analyzer.go
aws/access_analyzer_test.go
aws/access_analyzer_types.go
aws/aws.go

Updated [refactor access analyzer]

refactor access analyzer

---

aws/aws.go

Fix EC2 keypair nil pointer issue

Fix EC2 keypair nil pointer issue

---

aws/resources/opensearch.go

Fixes nil pointer issue https://app.circleci.com/pipelines/github/gruntwork-io/cloud-nuke/11891/workflows/ac2abde2-1217-4590-9b6d-c7af62210e4a/jobs/33592.

Fix nil pointer when first seen tag is nil

---

.circleci/nuke_config.yml

Add github role to exclude list.

dont delete github oidc role

---

README.md
config/config.go

Follow-up PR https://github.com/gruntwork-io/cloud-nuke/pull/570. 
Updating the README file for configuration usage with details. 

Update README for configuration usage

---

config/config.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/575. 
Tested running it locally. 

Fix yaml marshal logic for KMS key config

---

aws/aws.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/404

Remove unused variables and unused code

---

.circleci/nuke_config.yml

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/579. 

Fix configuration error sync

---

aws/resources/acm.go

Adding logs for ACM

---

.circleci/config.yml

Print debug level logs

---

aws/resources/acm.go

For https://github.com/gruntwork-io/cloud-nuke/issues/579. 

Add additional debug information for ACM troubleshooting

---

.circleci/config.yml
commands/cli.go

Add exclude resource tag for ACM and additional debug for config

---

go.mod

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/611.

Increase go version from 1.18 to 1.21

---

README.md

Fixes https://github.com/hongil0316/james-cloud-nuke/pull/17/files.

Update instruction for using cloud-nuke as a library

---

aws/resources/ec2.go
aws/resources/ec2_test.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/300

Release elastic IP address

---

README.md
aws/resource_registry.go
aws/resources/rds_parameter_group.go
aws/resources/rds_parameter_group_test.go
aws/resources/rds_parameter_group_types.go
config/config.go
config/config_test.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/645

Deleting DB Parameter Groups

---

.circleci/nuke_config.yml
README.md
aws/resource_registry.go
aws/resources/msk_cluster.go
aws/resources/msk_cluster_test.go
aws/resources/msk_cluster_types.go

- Fix MSK nuking
- Add MSK in recurring nuke jobs
Fix MSK nuking

MSK nuking fix

---

.circleci/config.yml
.gon_amd64.hcl
.gon_arm64.hcl

Fixed apple signing to use new sign tool.

Fixed apple signing

---

README.md
aws/resource_registry.go
aws/resources/ec2_internet_gateway.go
aws/resources/ec2_internet_gateway_test.go
aws/resources/ec2_internet_gateway_types.go
config/config.go
config/config_test.go

implementation ec2 internet gateway nuke

---

README.md
aws/resource_registry.go
aws/resources/ec2_subnet.go
aws/resources/ec2_subnet_test.go
aws/resources/ec2_subnet_types.go
config/config.go
config/config_test.go

Implemented ec2-subnet nuke

---

README.md
aws/resource_registry.go
aws/resources/common.go
aws/resources/ecs_cluster_types.go
aws/resources/security_group.go
aws/resources/security_group_test.go
aws/resources/security_group_types.go
config/config.go
config/config_test.go

security group implementation

---

README.md
aws/resource_registry.go
aws/resources/ec2_network_interface.go
aws/resources/ec2_network_interface_test.go
aws/resources/ec2_network_interface_types.go
config/config.go
config/config_test.go
util/error.go

implement network interface nuke

---

README.md

Added winget install instructions to readme
Updated Readme

Added winget install instructions to readme

---

README.md
aws/resource_registry.go
aws/resources/ec2_network_acl.go
aws/resources/ec2_network_acl_test.go
aws/resources/ec2_network_acl_types.go
config/config.go
config/config_test.go

implemented network acl nuke

---

aws/resources/ec2_egress_only_igw_test.go
aws/resources/ec2_network_interface_test.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/666

concurrent map write issue fix

---

aws/query_test.go
commands/cli_test.go

Fixing the unit test failure introduced with recent PR mix. 

Fix unittest

---

aws/resources/rds_parameter_group.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/717.

fix rds parameter default group nuke issue

---

.circleci/config.yml

Seeing build/test failures due to resource usage. Increasing the resource size to large. 

Increase the resource class from medium to large

---

aws/resources/security_group.go

Detaching the security group from another security group

---

.circleci/config.yml

Updated deprecated resource class in CircleCI

Update resource class to  macos.m1.medium.gen1

---

aws/query.go
aws/query_test.go
commands/cli.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/846

always protect until expire

---

aws/resource_registry.go
aws/resources/iam_instance_profile.go
aws/resources/iam_instance_profile_test.go
aws/resources/iam_instance_profile_types.go
config/config.go
config/config_test.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/852.

add aws iam instance profile

---

aws/resources/cloudtrail.go
aws/resources/cloudtrail_test.go
aws/resources/cloudtrail_types.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/838.

add tags support for cloudtrail

---

README.md

Improve + Update the README for available resources

---

aws/resources/s3.go
aws/resources/s3_test.go
aws/resources/s3_types.go

Fixes https://github.com/gruntwork-io/cloud-nuke/issues/872.

delete s3 bucket lifecycle

---

README.md
config/config.go
config/config_test.go

Fixes #https://github.com/gruntwork-io/cloud-nuke/issues/876.

Improve the tags filtering logic

---

aws/resources/ec2_vpc.go

Fixes #902.
Adds a nil check to fail gracefully if the DescribeVpcEndpoints call fails, for example because a user has insufficient permission in AWS.
Added nil-check after call to DescribeVpcEndpoints

fix(vpc): handle errors from DescribeVpcEndpoints in EC2 VPC endpoint

---

aws/resources/ecs_cluster.go
aws/resources/ecs_cluster_test.go

Fixes regex name filtering for ECS clusters that was not working correctly when using `names_regex` filters.
- When using wildcard regex `".*"`, all clusters were found
- When using specific patterns like `"abc123"`, no clusters were returned even when matching clusters existed
- The root cause was that name and time filtering logic were separated, causing name filters to be ignored
- Consolidated filtering logic to check both name and time filters together
- Simplified code by removing redundant helper functions
- Fixed `ShouldInclude` calls to pass both Name and Time values
- Added comprehensive test coverage for various filtering scenarios
- All existing tests pass
Fixes #900

fix(ecs-cluster): fix regex name filtering for ECS clusters
