gruntwork-io/cloud-nuke

- README.md
- aws/asg.go
- aws/asg_test.go
- aws/asg_types.go
- aws/aws.go
- aws/ebs.go
- aws/ebs_test.go
- aws/ebs_types.go
- aws/ec2.go
- aws/ec2_test.go
- aws/ec2_types.go
- aws/elb.go
- aws/elb_test.go
- aws/elb_types.go
- aws/elbv2.go
- aws/elbv2_test.go
- aws/elbv2_types.go
- aws/types.go
- commands/cli.go
- commands/errors.go
- util/unique_id.go
Adds support for nuking:
- Auto Scale Groups
- Elastic Load Balancers (Classic and v2)
- EBS Volumes
> aws-nuke v0.0.2

- README.md
- aws/ami.go
- aws/ami_test.go
- aws/ami_types.go
- aws/aws.go
- commands/cli.go
This PR does the following:
- Adds support for listing and nuking Amazon Machine Images owned by the user
- Adds tests for this functionality
> Nuke User owned AMIs

- aws/ami.go
- aws/asg.go
- aws/ebs.go
- aws/ec2.go
- aws/eip.go
- aws/elb.go
- aws/elbv2.go
- aws/snapshot.go
Currently when iterating over resource IDs and nuking each, cloud-nuke returns from the function when it encounters an error. This results in the other resources further down the list not being deleted on that pass.
This PR updates cloud-nuke to log when it encounters an error and continue with other resources in the list. This should greatly reduce the amount of leftover resources we see and should slightly reduce our monthly costs
> Improve nuking strategy

- README.md
- aws/aws.go
- aws/launch_config.go
- aws/launch_config_test.go
- aws/launch_config_types.go
This PR adds the ability to nuke launch configurations so we no longer run into our 200 limit.
This brings to light another interesting use case for cloud-nuke. We can consider nuking resources that have quantity limits on them so automated tests don't fail because we hit the limit
> Nuke Launch Configurations

- aws/elbv2_test.go
This replaces the `if err != nil { assert.Fail() }` calls with `require.NoError`. Aside from being slightly more readable, the switch to using `require` as opposed to `assert` allows the test to exit when it shouldn't continue. By doing so, we can avoid panics halting the test and leaving resources lying around like in [this failure](https://circleci.com/gh/gruntwork-io/cloud-nuke/5857).
> Fix panic from segfaults caused by continuing from a failed condition

- aws/aws.go
This PR fixes the constant `AuthFailure: AWS was not able to validate the provided access credentials` errors when running tests. It turns out that AWS added a new GovCloud region `us-gov-east-1` which I wasn't explicitly ignoring as I did the China and other GovCloud regions.
The simple change was to add `us-gov-east-1` to the `reservedRegions` array so we don't try to get resources from it
> Fix AuthFailure Error

- Gopkg.lock
- Gopkg.toml
- README.md
- aws/aws.go
- aws/eks.go
- aws/eks_test.go
- aws/eks_types.go
- aws/eks_utils_for_test.go
Given how expensive EKS is (one cluster = $0.20/hr), and how frequent the tests fail right now as I actively develop, I am afraid I might forget to clean up one of these so decided to go ahead and implement the nuking.
Note that this required upgrading `aws-sdk-go`. I tried the latest and there were issues, so downgraded to what we have in terratest.
> Nuke EKS clusters

- aws/ecs_utils_for_test.go
- aws/elbv2_test.go
v0.1.5 failed 3 times in a row because `us-east-1e` does not have capacity for ECS or EKS. This removes `us-east-1e` from consideration.
> Test stability: don't use us-east-1e

- aws/aws.go
- aws/eks.go
- aws/eks_test.go
- aws/eks_utils_for_test.go
I believe the latest cloud-nuke runs are failing because of this.
> Make sure we don't attempt to get EKS resources in an unsupported region

- aws/ecs_utils_for_test.go
- aws/elbv2_test.go
This is an attempt at stabilizing the tests:
- [This build](https://circleci.com/gh/gruntwork-io/cloud-nuke/9036) appeared to have failed because it picked some malformed subnets. Upon checking `getSubnetsInDifferentAZs`, it looked like it was pulling in all subnets for the region, so I added in a filter to only get the default subnets to see if that makes the build more consistent.
- [This build](https://circleci.com/gh/gruntwork-io/cloud-nuke/9020) failed because the ECS service could not be found when draining. I am guessing this is an eventual consistency issue, so added a wait right after creating the ECS service.
> Attempt to stabilize tests

- commands/cli_test.go
This fixes another test failure that occurs frequently. Specifically, anytime the tests run at midnight, `TestParseDuration` will fail. See https://circleci.com/gh/gruntwork-io/cloud-nuke/9388 for a sample failure output.
> Fix date boundary test failure

- commands/cli.go
Here is my take on addressing issue #26. Instead of exiting if the user types in an invalid input to the nuke prompt, the user will be notified that the input was invalid and prompted again. A note that you can exit with ^C is added as well.
> Prompt for 'nuke' again on invalid responses

- README.md
- aws/aws.go
- commands/cli.go
- Adds --dry-run flag to to exit after listing resources to nuke but before taking action.
- Fixing code bug where if no resources found cloud-nuke prompts user to nuke an empty list of resources.
> Add dry run and fixing bug which shows an empty list to nuke

- README.md
- commands/cli.go
This PR addresses #80 and #81:
- Adds the `--sg-only` flag to limit the command to only remove default security group rules and not delete default VPCs
- Adds the ability to include/exclude specific regions
This was trivial to add as the regions feature was already available in the `aws` subcommand, including tests.
> Improvements to defaults-aws command

- README.md
- aws/aws.go
- aws/rds.go
- aws/rds_test.go
- aws/rds_types.go
- commands/cli.go
Following #84.
From the first part:
> Add feature to delete RDS instances

- aws/aws.go
- aws/rds_cluster.go
- aws/rds_cluster_test.go
- aws/rds_cluster_types.go
This is a complement of #86.
The previous PR was deleting all types of RDS but the Aurora.
> Add feature to delete RDS Clusters

- Gopkg.lock
- aws/ecs_service.go
We weren't handling pagination in ECS service nuking before, so we weren't picking up the Fargate ECS services in our account, where we have more than 100 ECS clusters.
> Add logic for paging in ECS cluster nuking capability

- .circleci/config.yml
- aws/ec2_test.go
We've had a few test failures where cloud-nuke panics:
- https://circleci.com/gh/gruntwork-io/cloud-nuke/16853
- https://circleci.com/gh/gruntwork-io/cloud-nuke/16865
- https://circleci.com/gh/gruntwork-io/cloud-nuke/16860
This is bad, because panic stops all test threads, even the ones unrelated to the cause of panic, meaning that we skip any cleanup routines we have in testing. Normally, this isn't an issue as we have `cloud-nuke` to handle the cleanup. However, some of the tests create termination protected EC2 instances to test cloud-nuke's functionality to ignore those, and if we don't clean those up, then nothing will.
> Fix source of panic in tests

- aws/ec2_test.go
- aws/ecs_utils_for_test.go
Everytime cloud nuke selects a new region (e.g `eu-north-1`), the tests fail because they don't support `t2.micro`. This fixes that by using `t3.micro` for testing.
> Use t3.micro for testing, since t2.micro is largely deprecated in most regions

- aws/eip_test.go
- aws/rds.go
One of our recent nuking builds panicked when looking up RDS instances. Looking at the stack trace (https://circleci.com/gh/gruntwork-io/cloud-nuke/16971), it looks like the cause was an RDS instance with `InstanceCreateTime` set to `nil`. Not sure when this is `nil`, but nonetheless added the requisite guards to avoid it in the future.
Also ran `go fmt` and removed dead code (commented out import).
> Fix source of panic in RDS module

- .circleci/config.yml
- README.md
- aws/aws.go
- aws/s3.go
- aws/s3_test.go
- aws/s3_types.go
- aws/types.go
- commands/cli.go
This is an extension of #96 to prepare for merging into our environment. Specifically, our accounts are not ready to consider S3 buckets for nuking, but we also don't want to block the PR on our inaction to prep. So this extends the PR with a stopgap solution to exclude `s3` from consideration.
The main commit to look at and review is 15f7288, which introduces the `--exclude-resource-type` CLI arg and updates the circleci config to make use of it.
> Prepare #96 for merge

- README.md
- aws/aws.go
- aws/s3.go
- aws/s3_test.go
- aws/s3_types.go
This PR adds support to delete S3 buckets as requested in https://github.com/gruntwork-io/cloud-nuke/issues/58 
It ensures that the AWS S3 list bucket operation - which lists all buckets irrespective of region - is not called multiple times for each region and uses cached entries as highlighted in the above issue discussion. 
Deletion also uses ```WaitUntilBucketNotExists``` to ensure bucket is deleted. It also supports edge cases where in bucket is deleted by some other means after listing but before deletion.
**Demo:**
1. Added s3 to list of resources
```
go run main.go aws --list-resource-types | grep s3
s3
```
2. Run S3 related tests:
```
go test -run S3 -v ./...
=== RUN   TestListS3Buckets
time="2020-02-29T22:52:35+08:00" level=info msg="Random region chosen: ap-northeast-1" …
```
> Adding S3 nuke support

- README.md
- aws/aws.go
- aws/s3.go
- aws/s3_test.go
- aws/s3_types.go
- commands/cli.go
This PR adds the following features:
1. Support for --log-level flag on command line to control the logging.
**Demo**
```
go run main.go aws --resource-type s3 --log-level debug
```
or 
```
LOG_LEVEL=debug go run main.go aws --resource-type s3
```
Valid log types are mentioned in the corresponding readme change. 
2. Optimizing the `s3.getAllS3Buckets` function to get S3 bucket properties (region,tags) concurrently as opposed to getting for each one - this was added because running S3 bucket deletion for an account > 50 buckets was too slow and was taking around 1 sec per bucket to get its properties - which would lead to linear increase as per the number of buckets. 
`s3.getAllS3Buckets` now supports batchSize which is as per `aws.MaxConcurrentGetSize` in `s3_types.go` to get X buckets …
> Adding support for --log-level and concurrent S3 get

- README.md
`cloud-nuke` use go modules, no longer uses dep. Language can be removed from `README` to reflect this change
> remove dep language from README

- aws/s3.go
- aws/s3_test.go
- util/errors.go
This fixes a few bugs in the s3 deletion routine:
- `cloud-nuke` can crash with OOM if there are too many objects in the bucket. This is because it loads all the objects into memory before starting to delete them. **This was fixed by combining the deletion routine with the pager.**
- No error was returned if there was an error emptying the bucket. This led to confusing error messages where it may have failed to empty the bucket, but cloud-nuke exits because it can't delete the bucket itself. **This was fixed by updating the routine to return a combined error for all the buckets**
- Tests were not checking errors in the nuke routine, so it would exit with a pass even when the nuking failed.
> Memory efficient s3 delete

- aws/ami_test.go
- aws/ecs_cluster.go
- aws/ecs_cluster_test.go
Hey, this PR is aiming to add filtering to ECS Clusters. The issue I was seeing is described here: https://github.com/gruntwork-io/cloud-nuke/issues/145
**Overview:** 
In some scenarios, the ECS Clusters TagResource function would be called while the cluster is not in `ACTIVE` state. This meant that the tests we have fail, and also the code itself was flawed. 
**It has now been updated:**
- `cloud-nuke ecscluster` will nuke ECS Clusters which are also set as `ACTIVE` or `PROVISIONING`
- `PROVISIONING` is also part of the condition, as the assumption is the cluster will be discoverable, and its state is going towards being `ACTIVE`
- all other states (`INACTIVE`, `DEPROVISIONING`, `FAILED`) are not relevant and therefore used in this functionality (you can't tag a cluster that's not …
> Fix for inactive ecs clusters

- .circleci/config.yml
CircleCi builds that run on a schedule run on behalf of some CircleCi machine user, and that machine user does not have access to our CircleCi contexts. As a result, all the builds show up as "unauthorized":
> Remove contexts from scheduled builds

- .circleci/config.yml
In #154, I accidentally missed removing the context from the `test` jobs in the scheduled workflows 🤦
> Remove context from test jobs too

- aws/aws.go
This fixes the region finder logic to work with GovCloud. AFAICT, the rest of the functionality is compatible with GovCloud already. This was tested out by a customer. See [relevant slack thread](https://gruntwork-io.slack.com/archives/CLDULACTZ/p1611694482002400).
> GovCloud compatibility

- .circleci/config.yml
- .circleci/nuke_config.yml
This updates the CircleCI config to run nuke jobs for S3 buckets. To avoid deleting buckets that we expect to use, this adds a config file with the regex list that we have been using in the `aws-gc.py` script.
Note that I also updated the nuke jobs to not depend on the tests passing. It seems unnecessary to continuously run tests for every nuke job, especially since they are fairly slow. Not to mention that they are flaky and transiently fail, causing us to skip a nuke cycle.
> Nuke gruntwork S3 buckets

- aws/ami.go
[#161 ](https://github.com/gruntwork-io/cloud-nuke/issues/161)
Log the actual count of AMIs deleted.
I tried running the tests, but my AWS educate account doesn't have enough permissions to run them properly.
Its a simple change though.
> Log accurate number of AMIs deleted

- .circleci/config.yml
There appears to be a bug in the implementation of the transit gateway nuking job that causes our account nuking CI job to fail. See [this failing build](https://app.circleci.com/pipelines/github/gruntwork-io/cloud-nuke/3272/workflows/466051ad-35fb-47b4-a5e4-5ba89d1db316/jobs/24002) for example.
Note that it does not appear to be IAM permission related, as the transit gateway related IAM permissions are all nested under `ec2`, which our CI user has full access to.
This PR disables nuking those resources until we can find a resolution.
> Exclude transit gateway resources from nuking job

- go.sum
```
go: github.com/gruntwork-io/gruntwork-cli@v0.7.0: missing go.sum entry; to add it:
go mod download github.com/gruntwork-io/gruntwork-cli
```
relates to Homebrew/homebrew-core#74233
> sync go.sum

- .circleci/config.yml
This should pick up the latest versions of Go and the `build-go-binaries` script, which should build binaries for Darwin ARM 64. Hopefully, this fixes #190.
I've also updated the build to not require the tests to pass on release builds when publishing binaries.
> Update to latest CircleCi image; don't require tests to pass when building binaries

- .circleci/nuke_config.yml
- README.md
- aws/aws.go
- aws/secrets_manager.go
- aws/secrets_manager_test.go
- aws/secrets_manager_types.go
- config/config.go
- config/config_test.go
- config/mocks/secrets_manager_cleanup.yaml
- config/mocks/secrets_manager_empty.yaml
- config/mocks/secrets_manager_empty_filters.yaml
- config/mocks/secrets_manager_empty_rules.yaml
- config/mocks/secrets_manager_exclude_names.yaml
- config/mocks/secrets_manager_filter_names.yaml
- config/mocks/secrets_manager_include_names.yaml
- go.sum
This includes support for nuking Secrets Manager secrets, including usage of the config file to restrict what secrets should be nuked, and an update to our config file to ensure that only test secrets manager secrets are deleted in our environment.
NOTE: This was prompted from our internal investigation in to the AWS bill (notes available in notion).
> Add support for nuking secrets manager secrets

- .circleci/config.yml
- aws/rds_cluster_test.go
- Remove exclusion for transit gateway. Not sure why we had some exclusions there for our nuke jobs, since we don't use transit gateway internally.
- Add logging to find the regions where the RDS cluster test fails (I had a few builds where it failed, but couldn't discern the region).
> Attempt to stabilize build

- README.md
- aws/access_analyzer.go
- aws/access_analyzer_test.go
- aws/access_analyzer_types.go
- aws/aws.go
- config/config.go
- config/config_test.go
We hit limits in our testing account for the multi region IAM Access Analyzers module, so I decided to use `cloud-nuke` to clear house and get a feature out of it. This PR was used to clear out residual access analyzers in our test account.
> Add functionality to nuke AWS IAM Access Analyzers

- config/config.go
- config/config_test.go
Fixes #198.
Refactored the function `ShouldInclude` to behave properly when there is a `exclude` but no `include` config. I added a unit test to this function that catches the bug in question.
> Fix Config file not including when there is a 'exclude' rule

- README.md
- aws/aws.go
- aws/cloudwatch_dashboard.go
- aws/cloudwatch_dashboard_test.go
- aws/cloudwatch_dashboard_types.go
- aws/secrets_manager_test.go
- config/config.go
- config/config_test.go
> Nuke cloudwatch dashboard

- README.md
- aws/aws.go
- aws/ec2_types.go
- aws/ec2_vpc.go
This takes the existing VPC code and implements it for non-default per region nuking.
> support deleting vpcs that are non-default

- .circleci/config.yml
When we merged in https://github.com/gruntwork-io/cloud-nuke/pull/243, we started nuking VPCs in our accounts. Normally this isn't a problem, but there are two issues with this that make it disruptive to our test flow:
- The VPC feature doesn't honor the `--older-than` parameter, so it will start nuking all VPCs regardless of when they were created. This is disruptive to our tests as it can start nuking a VPC that is being used in testing.
- The VPC feature doesn't honor the config file, so we can't exclude certain VPCs. We have a VPC in our sandbox test account that we use for demos that we don't want nuked, and currently there isn't a way to exclude that from nuking consideration.
This PR updates our periodic nuking routine so that it excludes the VPCs for now, until we implement the …
> Exclude VPC from periodic nuking

- go.mod
Noticed that `go.mod` references to go 1.13 but in CI/CD is used go 1.16
> Updated go.mod version 1.16

- aws/secrets_manager_test.go
Included changes:
* separated secret name for each test
* added retries to check if created secret is available, instead of fixed 15s waiting 
Result:
Fixes:
#227
> #227 Fix for TestListSecretsManagerSecrets TestTimeFilterExclusionNewlyCreatedSecret

- aws/aws.go
- aws/ec2_utils_for_test.go
- aws/opensearch_test.go
- aws/sqs_test.go
- aws/transit_gateway_test.go
Included changes:
* Excluded region ap-northeast-3 from OpenSearch tests since can't be deployed t3.small.search instances there
* Updated TestNukeTransitGatewayVpcAttachment to use distinct subnets by AZ
* Added check for SQS queue availability
Fixes failures like:
```
=== RUN   TestCanTagOpenSearchDomains
=== PAUSE TestCanTagOpenSearchDomains
=== CONT  TestCanTagOpenSearchDomains
[cloud-nuke] time="2022-01-12T21:57:13+02:00" level=info msg="Random region chosen: ap-northeast-3"
opensearch_test.go:124: 
Error Trace:	opensearch_test.go:124
opensearch_test.go:29
Error:      	Received unexpected error:
InvalidTypeException: Invalid instance type: t3.small.search
Test:       	TestCanTagOpenSearchDomains
--- FAIL: TestCanTagOpenSearchDomains (2.76s)
=== CONT …
```
> Failing tests fixes

- .circleci/nuke_config.yml
- README.md
- aws/aws.go
- aws/oidc_provider.go
- aws/oidc_provider_test.go
- aws/oidc_provider_types.go
- config/config.go
- config/config_test.go
This adds IAM OpenID Connect Provider for nuking consideration. I implemented this to clean up residule OIDC providers in `phxdevops` since that caused us to reach AWS limits there in our testing.
> Include OpenID Connect Providers to nukable resource

- .circleci/nuke_config.yml
- README.md
- aws/aws.go
- aws/cloudwatch_loggroup.go
- aws/cloudwatch_loggroup_test.go
- aws/cloudwatch_loggroup_types.go
- config/config.go
- config/config_test.go
This is an extension of https://github.com/gruntwork-io/cloud-nuke/pull/250, with the following fixes:
- Resolve merge conflict
- Add nuke config for our environments
- Add support for filtering by name, specified via config file
- Add support for filtering by creation time
- Make delete call concurrently in batches
- Support paging through list of cloudwatch log groups, instead of just getting the first page
> Cloudwatch Log Group Nuking

- README.md
- aws/aws.go
- aws/kms_customer_key.go
- aws/kms_customer_key_test.go
- config/config.go
- config/config_test.go
Updated KMS Customer key removal to support regexp configurations under `KMSCustomerKeys` key, implementation supports inclusion and exclusion.
Closes: https://github.com/gruntwork-io/cloud-nuke/issues/280
> #280 Regexp expressions in KMS Customer key removal 

- aws/ec2.go
- aws/ec2_vpc.go
- aws/ec2_vpc_test.go
Fixes #288 
* Move VPC tagging logic outside of filter function, allows for easier testing of `shouldIncludeVpc`
* Remove `TestListVpcsWithConfigFile`, replacing with `TestShouldIncludeVpc`. Table based unit tests are more efficient and can easily test several use cases at once.
> Filter VPCs by name instead of VPC ID

- .circleci/nuke_config.yml
- README.md
- aws/aws.go
- aws/eks.go
- aws/eks_test.go
- config/config.go
- config/config_test.go
In our account where we are running `cloud-nuke`, we have a ghost EKS cluster that shows up in the list API, but will return a 404 if you try to get the details. This EKS cluster will presumably be garbage collected by AWS eventually, but in the meantime, it causes problems by halting execution of `cloud-nuke` everytime it tries to nuke our account.
This PR works around this limitation by adding config support to EKS cluster nuking, and adding an explicit exclude rule to ignore the ghost cluster.
> Add config support for EKS and exclude ghost cluster in our account

- aws/ec2.go
- aws/ec2_unit_test.go
- aws/mock_ec2_utils_for_test.go
Fixes #285.
- Moves VPCE deletion to before subnet deletion
- Adds `waitForVPCEndpointsToBeDeleted` to ensure Interface endpoints (which can take a few minutes to delete) are no longer in the 'deleting' state. Without this, the endpoints will be marked for deletion (`state=deleting`), but nuking the subnet immediately after will still fail with the same `DependencyViolation` error. Only when the VPCEs are `state=deleted` will the subnet nuke succeed.
Scenario: 1 VPC with 5 VPCEs (x4 Interfaces, x1 gateway)
Output from `cloud-nuke aws --resource-type vpc` (v0.11.3):
```
[cloud-nuke] INFO[2022-04-10T10:37:51+01:00] The following 1 AWS resources will be nuked: 
[cloud-nuke] INFO[2022-04-10T10:37:51+01:00] * vpc vpc-0dcb3d0c8a63e90ff eu-west-2        
[cloud-nuke] …
```
> Ensure VPCEs are deleted before attempting to delete subnets

- aws/s3.go
- aws/s3_test.go
… refuses deletion
This fixes a bug where you run into the problem when deleting s3 buckets but they have a bucket policy that prohibits deleting the entire bucket. 
The fix ensures that the bucket policy is cleared before attempting to delete the bucket.
Solves the Issue #213
> Delete s3 BucketPolicy before nuke Bucket to avoid errors when policy… 

- README.md
- aws/aws.go
- aws/inspect.go
- aws/inspect_test.go
- aws/types.go
- aws/types_test.go
- commands/cli.go
- go.mod
- go.sum
These changes introduce non-destructive "inspect" functionality with the same semantics and parameters as the destructive nuke functionality. As `nuke` is to `DELETE` , `inspect` is to `READ` or `LIST`. 
Non-destructively inspecting resources with cloud-nuke can be useful in CI/CD jobs, preflight checks, and anywhere else that you may wish to ensure that resources: 
- are, or are not, in a given AWS account
- are, or are not, within a given AWS region
There are two ways to consume this new inspect functionality: 
- Via the command-line interface and a new `inspect-aws` command. This command is mostly identical to the `aws` command, but it will never destroy resources and can accept many of the same flags.
- Via a new method `InspectResources` that can be used as a library function for …
> Extend cloud-nuke with non-destructive inspect command & library methods

- aws/inspect.go
- commands/cli.go
This fixes the regression bug that was introduced in https://github.com/gruntwork-io/cloud-nuke/pull/305, where the `--exclude-resource-type` no longer handled exclusions correctly.
> Fix resource-type include exclude flags

- .circleci/nuke_config.yml
Avoids the main circle-ci-test user when nuking IAM Users. Also adds a few more test buckets that should be deleted.
N/A
> Avoid more resources

- .circleci/config.yml
This updates the nuke circleci rules to use the CircleCI context instead of using env vars.
> Attach nuke permissions by circleci context, not env var

- README.md
Fixes #314.
- Updated the README so that the config key for NAT Gateways filtering is correct.
None.
> fix: Config key typo in README for NAT Gateways

- aws/nat_gateway.go
This fixes a bug where if the nat gateway was already deleted and in the deleted state, subsequent runs would still list it as needing to be deleted, however thankfully the AWS API would not error on subsequent runs, but it would appear that resources were not being cleaned up.
> fix a bug where deleted nat gateways were included in nuke list

- aws/nat_gateway.go
- aws/nat_gateway_test.go
~~Solves https://github.com/gruntwork-io/cloud-nuke/issues/310.~~
Edit: I initially thought it would solve issue number 310, but the real problem is in the README.md since it's misleading and doesn't match with the Config key in the Go code (https://github.com/gruntwork-io/cloud-nuke/blob/master/config/config.go#L16). So this PR actually just adds a test and verifies that the code works properly (which it does), and adds a small verification step in the lookup function to make sure that it doesn't retrieve NAT gateways that are deleted or in deletion.
- Added test to verify that looking up NAT Gateways with the configuration file works.
- Updated the …
> update: Skips deleted and in deletion NAT gateways from nuking, adds test for config file lookup

- aws/nat_gateway.go
This fixes a bug in the NatGateway nuke routine where the wait routine ignored `NatGatewayNotFound`.
```
[cloud-nuke] INFO[2022-07-07T13:10:06-05:00] Waiting for all NAT gateways to be deleted. returned an error: FatalError{Underlying: NatGatewayNotFound: NAT gateway nat-0f23ac5d3265a98ff was not found
status code: 400, request id: 578dc5b2-d2b1-4906-8bd0-650a6826e2fc}. Attempt 1 of 30. Sleeping for 10s and will retry.
[cloud-nuke] INFO[2022-07-07T13:10:16-05:00] Waiting for all NAT gateways to be deleted.
[cloud-nuke] INFO[2022-07-07T13:10:16-05:00] Waiting for all NAT gateways to be deleted. returned an error: FatalError{Underlying: NatGatewayNotFound: NAT gateway nat-0f23ac5d3265a98ff was not found
status code: 400, request id: 1a31f4d5-9943-46d8-aea1-8f4f52bd9cf1}. Attempt 2 of 30. …
```
> Handle NatGatewayNotFound

- .circleci/config.yml
It turns out that we haven't been running the nuking routines due to the CircleCI triggers changing it's permissions model to no longer support scheduled workflows. Instead, we need to migrate to using [scheduled pipelines](https://circleci.com/docs/scheduled-pipelines). This PR updates the CCI config to start supporting scheduled pipelines.
(no functional changes)
> Fix circleci pipeline to use scheduled pipelines

- README.md
- aws/aws.go
- aws/macie.go
- aws/macie_test.go
- aws/macie_types.go
- util/get_current_account_id.go
Fixes #322 by implementing support for "nuking" Macie accounts that were created by Invitation only. (Macie member accounts created via AWS Organizations do not have sufficient permissions to disassociate _themselves_ from the Org). 
Programmatic testing with Macie is pretty awkward. I found that you can continuously accept an invite from another account to become a member account, then disassociate yourself (nuke), then re-use the same standing invitation to re-associate yourself as a member account. I'm currently using this workaround to leave a "standing" invite from our phxdevops account in `us-east-1` for sanity. 
We could expand our test coverage out to other regions, but that would just require maintaining a map of regions to standing invitation IDs.
Furthermore, Macie member …
> Implement support for Macie member accounts

- aws/aws.go
- aws/macie.go
Removes unused parameters from `getAllMacieMemberAccounts` per discussion [here](https://github.com/gruntwork-io/cloud-nuke/pull/323#discussion_r923663400).
> Remove unused variables from getAllMacieMemberAccounts

- .circleci/nuke_config.yml
- .gitignore
- README.md
- aws/aws.go
- aws/iam_role.go
- aws/iam_role_test.go
- aws/iam_role_types.go
- aws/macie_test.go
- aws/types.go
- config/config.go
- config/config_test.go
These changes are based on #251, but also introduce concurrent deletion of roles for speed. They introduce support for inspecting and nuking IAM Roles. 
> Implement support for IAM Roles

- aws/ec2.go
- aws/ec2_test.go
- aws/ec2_unit_test.go
- aws/mock_ec2_utils_for_test.go
Fix nukeSecurityGroup to delete all ingess/egress rule before deleting security group.
and added testing code that using existing method.
Fixes #316.
> Fix nukeSecurityGroup for delete chained-security-group

- aws/elasticache.go
- aws/elasticache_test.go
Fixes #333 
These changes introduce support for nuking elasticache clusters that are members of a replication group. The single nuke method has been extended to handle both cases: 
1. Cache cluster is not a member of a replication group, and so can be deleted directly 
2. Cache cluster is a member of a replication group, which itself must then be deleted, because attempting to delete the member cache cluster itself will fail as long as the replication group exists. 
In testing against a deployed Ref Arch, these changes resolve the issue observed in #333.
> Support nuking elasticache replication groups

- aws/elasticache.go
Fixes #341.
- Look up replication groups separately. Previously we were trying to look up all cache nodes via `DescribeCacheClusters`, which _will_ return nodes that are members of a ReplicationGroup - but won't signify which need to be passed through the ReplicationGroup code path. Instead, we first look up replication groups via their dedicated method `DescribeReplicationGroups` then issue a call to `DescribeCacheClusters`, specifying that the call should only return cache nodes that are not members of a replication group. 
- When then flatten both cache cluster types together, returning both types from the list method
- When nuking an elasticache cluster - return immediately if the cluster is found to be of type `Replication` - previously, incorrect fallthrough behavior was causing …
> Fix elasticache cluster nuking

- README.md
- aws/apigateway.go
- aws/apigateway_test.go
- aws/apigateway_types.go
- aws/apigatewayv2.go
- aws/apigatewayv2_test.go
- aws/apigatewayv2_types.go
- aws/aws.go
- config/config.go
- config/config_test.go
- config/mocks/apigateway_empty.yaml
- config/mocks/apigateway_empty_filters.yaml
- config/mocks/apigateway_empty_rules.yaml
- config/mocks/apigateway_exclude_names.yaml
- config/mocks/apigateway_exclude_names.yml
- config/mocks/apigateway_filter_names.yaml
- config/mocks/apigateway_include_names.yaml
- config/mocks/apigatewayv2_empty.yaml
- config/mocks/apigatewayv2_empty_filters.yaml
- config/mocks/apigatewayv2_empty_rules.yaml
- config/mocks/apigatewayv2_exclude_names.yaml
- config/mocks/apigatewayv2_filter_names.yaml
- config/mocks/apigatewayv2_include_names.yaml
Fixes #349.
Implement support for inspecting and nuking API Gateways (v1 and v2).
> Implement support for API Gateway v1 and v2 

- README.md
- aws/aws.go
- aws/sns.go
- aws/sns_test.go
- aws/sns_types.go
- go.mod
- go.sum
Fixes #173 .
Implement support for inspecting and nuking SNS Topics.
> Implement support for SNS Topics

- aws/apigatewayv2.go
- aws/apigatewayv2_test.go
- aws/apigatewayv2_types.go
- commands/cli.go
Fixes https://github.com/gruntwork-io/company/issues/519
Fixes a bug that was preventing API Gateway v2 nuking from working properly.
> Fix API Gateway v2 nuking behavior

- .circleci/config.yml
These changes temporarily exclude IAM groups and IAM policies from the nuke routine run on Gruntwork test accounts. 
> Temporarily avoid nuking IAM groups and policies in GW test accounts

- README.md
- aws/iam_role.go
- aws/iam_role_test.go
Closes [CORE-285](https://gruntwork.atlassian.net/browse/CORE-285)
This PR implements functionality to nuke IAM EC2 Instance Profiles that are attached to IAM roles being nuked.
In the AWS console when you create an IAM role with an EC2 trust relationship, AWS automatically creates and links the instance profile required for EC2 instances to assume to the role. Subsequently when you delete an IAM role that has an attached instance profile from the console, AWS will automatically delete the instance profile along with it. When the CLI is used, instance profiles must be manually created, attached, and deleted as separate API actions.
cloud-nuke existing functionality detaches any instances profiles before attempting to delete IAM roles, but it does not delete the instance profiles, causing …
> Support nuking IAM EC2 instance profiles with roles - CORE-285

- aws/ami_types.go
- aws/asg_types.go
- aws/cloudwatch_dashboard_types.go
- aws/dynamodb_types.go
- aws/ebs_types.go
- aws/ec2_types.go
- aws/ecs_cluster_types.go
- aws/ecs_service_types.go
- aws/eip_types.go
- aws/elasticache_types.go
- aws/elb_types.go
- aws/elbv2_types.go
- aws/iam_group_types.go
- aws/iam_policy_types.go
- aws/iam_role_test.go
- aws/iam_role_types.go
- aws/iam_types.go
- aws/kms_customer_key_types.go
- aws/lambda_types.go
- aws/launch_config_types.go
- aws/rds_cluster_types.go
- aws/rds_types.go
- aws/sagemaker_notebook_instance_types.go
- aws/snapshot_types.go
- aws/sqs_types.go
Reduces the batch sizes on all resources where the AWS rate limits were a guess such that two instances of cloud nuke could be running on an account without expecting any issues.  This should enable cloud-nuke to run better in automated environments as well as reduce the likelihood of manual activity in the AWS account interfering.
This is a stopgap solution to the rate limit issue and we plan to implement a more robust approach in the future.
Updated max batch size on many resources to reduce rate limit errors.
> CORE-188 rate limits

- README.md
- aws/aws.go
- aws/ec2_key_pair.go
- aws/ec2_key_pair_test.go
- aws/ec2_key_pair_types.go
- config/config.go
- config/config_test.go
Fixes https://gruntwork.atlassian.net/browse/CORE-284.
* Tested running the cloud-nuke command line locally to delete an existing EC2 key pair
```
aws-vault exec gruntwork-customer-access-test -- go run main.go aws --resource-type ec2-keypairs
```
* Unit tests that creates & nuke an EC2 key pair. 
* Tested `aws-inspect` on ec2 key pair
```
aws-vault exec gruntwork-customer-access-test -- go run main.go inspect-aws --resource-type ec2-keypairs
```
> Add support to delete ec2 key pairs using cloud-nuke

- README.md
- aws/aws.go
- aws/kms_customer_key.go
- aws/kms_customer_key_test.go
- aws/kms_customer_key_types.go
Closes [CORE-292](https://gruntwork.atlassian.net/browse/CORE-292)
This PR adds functionality to nuke KMS Key Aliases with KMS keys that are being nuked.
* This does not change existing cloud-nuke KMS Key filtering functionality
* Key aliases will only be nuked if they are attached to a KMS key that is being nuked
Added support for deletion of KMS Key Aliases
> Support deletion of KMS Key Aliases - CORE-292

- .circleci/nuke_config.yml
I noticed there were some more buckets accumulating in phx devops account that were not listed here. So I added some more patterns to this list. I don't know where some of these buckets are coming from because they are from repos I don't have access to, so please do a sanity check if this list seems reasonable.
Also added some log group tests that were not in the list.
> add more patterns to nuke

- .circleci/config.yml
Increases CircleCi build reliability by using a bigger worker with lower parallelism.
Updated build steps.
> update worker size and build parallelism

- README.md
- aws/aws.go
- aws/ec2_dedicated_host.go
- aws/ec2_dedicated_host_test.go
- aws/ec2_dedicated_host_types.go
- config/config.go
- config/config_test.go
Closes [CORE-286](https://gruntwork.atlassian.net/browse/CORE-286)
Add support for nuking EC2 Dedicated Hosts
[CORE-286]: https://gruntwork.atlassian.net/browse/CORE-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-286]: https://gruntwork.atlassian.net/browse/CORE-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Support nuking EC2 Dedicated Hosts - CORE-286

- aws/ec2_unit_test.go
- aws/ecs_utils_for_test.go
- aws/elasticache_test.go
- aws/mock_ec2_utils_for_test.go
Included changes:
* usage of newer image ID used in ECS tests
* updated pattern used elasticate test to be more specific
* updated missing mocks used in VPC removal tests
> Cloud nuke failing tests fixes

- .circleci/config.yml
- README.md
- aws/aws.go
- aws/ecr.go
- aws/ecr_test.go
- aws/ecr_types.go
- config/config.go
- config/config_test.go
Fixes [CORE-381](https://gruntwork.atlassian.net/browse/CORE-381).
[CORE-381]: https://gruntwork.atlassian.net/browse/CORE-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement ECR support

- README.md
- aws/aws.go
- aws/rds.go
- aws/rds_test.go
- config/config.go
- config/config_test.go
Fixes #389. Adds documentation for RDS db resource type and adds support for Config file filtering for DBInstance resources
Added DBInstance resource type support to config files.
> CORE-332 Document RDS, Neptune, Document DB

- aws/ec2.go
- aws/ec2_unit_test.go
Fixes #400.
Updated `defaults-aws` to nuke IPv6 security group's egress rule
> `defaults-aws` also nukes the SG's IPv6 egress rule

- README.md
- aws/aws.go
- aws/launch_template.go
- aws/launch_template_test.go
- aws/launch_template_types.go
- config/config.go
- config/config_test.go
Fixes [CORE-312](https://gruntwork.atlassian.net/browse/CORE-312).
Added support for Launch Templates
[CORE-312]: https://gruntwork.atlassian.net/browse/CORE-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CORE-312] Implement Launch Template Support

- .circleci/config.yml
- README.md
- aws/aws.go
- aws/config_recorder.go
- aws/config_recorder_test.go
- aws/config_recorder_types.go
- aws/config_service.go
- aws/config_service_test.go
- aws/config_service_types.go
- aws/ecr.go
- aws/ecr_test.go
- config/config.go
- config/config_test.go
Fixes #000.
Added support for inspecting and nuking configservice recorders and rules
> Implement support for configservice recorders and rules

- README.md
Adds documentation to readme around VPC resource deletion bug
Updated readme with instructions for VPC deletion
> Document strange VPC deletion behavior

- .circleci/config.yml
- .circleci/nuke_config.yml
Updates the internal cleanup job to delete kms keys and vpcs.
> cleanup vpcs and kms keys in phxdevops

- README.md
- aws/aws.go
- aws/iam_role.go
- aws/iam_service_linked_role.go
- aws/iam_service_linked_role_test.go
- aws/iam_service_linked_role_types.go
- config/config.go
This code allows for IAM Service Linked Roles to be deleted.
In the Gruntwork Reference Architecture, we need to clean up AWSServiceRoleForAutoScaling.
Note that this is a naive approach; it requests the resource be deleted, but doesn't verify that they are actually deleted.
We could do this verification by capturing the DeletionTaskId and then querying for the deletion status until the status is (hopefully) SUCCEEDED. Alternate statuses are NOT_STARTED, IN_PROGRESS, and FAILED.
Thoughts here appreciated.
Fixes CORE-481
Added ability to nuke [IAM Service Linked Roles](https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html)
> CORE-381/Add deletion of IAM Service Linked Roles

- .circleci/config.yml
Adds exclusion for service-linked roles for auto-nuking.
> Exclude service-linked IAM roles

- aws/ec2.go
Nuke VPC Endpoints before nuking network interfaces.
Fixes #431 .
> Fix VPC endpoint removal failure

- README.md
- aws/aws.go
- aws/cloudwatch_alarm.go
- aws/cloudwatch_alarm_test.go
- aws/cloudwatch_alarm_types.go
- aws/cloudwatch_dashboard_types.go
- config/config.go
Fixes #429 .
Add CloudWatch Alarm support (include MetricAlarm and CompositeAlarm).
> Add cloudwatch alarm support (#429)

- README.md
These changes remove redundant verbiage from our README that was repeated on every line. It moves our current support for AWS resources into an easy-to-scan table: 
Simplified README by adding a markdown table displaying AWS resource support.
> Simplify presentation of which resources are supported

- aws/secrets_manager.go
- aws/secrets_manager_test.go
Fixes #435 .
Added test for deletion secret replica.
Update nuking secrets manager can nuke secret replica.
> Fix secrets manager can nuke secret replica.

- commands/cli.go
Optimize the nuke command to skip calling unnecessary functions on non-target regions
Updated nuke flow to skip unnecessary function calls on non-target regions
> Only run the nuke function if there are resources in the region to nuke

- aws/ebs.go
- aws/ebs_test.go
- aws/snapshot.go
- Add filter to only list available and creating ebs volumes
- Add filter to only list completed ebs snapshots
Adds filters for EBS Volumes and EBS Snapshots.
For EBS Volumes - Introduce a filter to only list volumes with the status of "available", "creating", or "error" This will filter out any volume in the "in-use", "deleting", or "deleted" status.
This change should reduce the number of "volume in use" errors seen by those running cloud-nuke, since volumes that are in the "in-use", "deleting", or "deleted" statuses can't be deleted.
For EBS Snapshots - Introduce a filter to only list ebs snapshots with a status of "completed" or "error". This will filter out any snapshot with either a "pending" status.
Read the [Gruntwork contribution …
> chore(CORE-659): Improve filtering for EBS Volumes and Snapshots

- README.md
- aws/ami.go
- util/has_aws_backup_tag.go
Closes [CORE-664](https://gruntwork.atlassian.net/browse/CORE-664)
Updated AMI filtering to exclude any images created by AWS Backup by checking for the reserved `aws:backup:source-resource` tag
Test run against `phxdevops` excluded the two images created by AWS Backup in `us-west-2`
Updated AMI filtering to exclude images created by AWS Backup
[CORE-664]: https://gruntwork.atlassian.net/browse/CORE-664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bug: Filter out AMIs created by AWS Backup - CORE-664

- README.md
- aws/aws.go
- commands/cli.go
Updates telemetry to be more obvious in readme and send fewer events.
Updated telemetry to be more obvious in readme and send fewer events.
> Make telemetry more obvious and reduce event count

- .circleci/config.yml
Fixes [CORE-562].
- Updates `nuke-sandbox` job to clean VPCs & unaliased KMS keys older than 24h
[CORE-562]: https://gruntwork.atlassian.net/browse/CORE-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CORE-562] Delete VPCs and unaliased KMS keys in sandbox account

- aws/aws.go
- commands/cli.go
- go.mod
- go.sum
- telemetry/telemetry.go
Fixes issue where telemetry could kill the process.
Updated telemetry module to not exit when an error is encountered
> Fix for cloud-nuke telemetry errors

- aws/cli_nuke.go
- aws/inspect.go
Obnoxiously, cloud-nuke currently logs to `STDOUT` by default, which interferes with several use-cases. For one, using the library in a Terminal User Interface (TUI) context.
These changes remove the hard-coded log line in the `InspectResources` method, which only accepts a query, and therefore exists squarely in the library usage context.
Required by https://github.com/gruntwork-io/gruntwork/pull/152
> Don't log to `STDOUT` when being used as a library

- README.md
- aws/aws.go
- aws/elasticache.go
- aws/redshift.go
- aws/redshift_test.go
- aws/redshift_types.go
- config/config.go
- config/config_test.go
Adds support for nuking redshift clusters
Added support for nuking redshift clusters
Warning, this PR adds support for a new resource! If you don't want to remove redshift clusters you will need to add configuration to a config file or using cli arguments
> add support for redshift

- README.md
- aws/aws.go
- aws/security_hub.go
- aws/security_hub_test.go
- aws/security_hub_types.go
Closes CORE-364
Adds support for nuking Security Hub
Security Hub itself is simply enabled/disabled for each region, however each instance must be cleared of Member Account links and administrator account links. 
This PR adds the ability for cloud-nuke to:
* Check if security hub is enabled, disable if so after
* Disassociating and deleting any member accounts
* Disassociating any administrator accounts
Supports the use of time filter, but does not support the use of configObj regex filtering (as there is only one instance per region that is enabled or disabled - technically it is named `default` but there is no control over this).
Additional testing was done manually with multiple AWS accounts to ensure the proper functionality of the member disassociation/deletion and administrator …
> Add support for Security Hub - CORE-364

- externalcreds/creds.go
Fixes #000.
Disable telemetry when cloud-nuke is used as a library.
> Hot patch: disable telemetry for library usage

- .circleci/config.yml
- .circleci/nuke_config.yml
Fixes tests which depend on iam-groups.
Added regex config for iam groups
> fix iam groups nuke job

- README.md
- aws/aws.go
- aws/rds_subnet_group.go
- aws/rds_subnet_group_test.go
- aws/rds_subnet_group_types.go
- config/config.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/471. 
Added [Added a new resource DB Subnet Groups to cloud-nuke functionality]
> Implement nukeAllRdsDbSubnetGroups to delete all RDS subnet groups

- aws/aws.go
- aws/ec2_vpc.go
- aws/ecs_cluster.go
- aws/globals.go
- aws/sns.go
- aws/sns_test.go
- config/config.go
- config/config_test.go
Fixes #359 and #480.
Adds the ability to include/exclude SNS topic by name for nuking. Additionally, the ability to exclude SNS topics by time is also added.
Adds the ability to include/exclude SNS topic by name for nuking. Additionally, the ability to exclude SNS topics by time is also added.
> add sns filter by name and time

- README.md
- aws/aws.go
- aws/backup_vault.go
- aws/backup_vault_test.go
- aws/backup_vault_types.go
- config/config.go
- config/config_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/446.
updated [Support backup-vault nuke]
> Support backup-vault nuke

- .circleci/nuke_config.yml
Configuration Only, updates default config to keep management vpcs
> don't nuke management vpcs

- .circleci/nuke_config.yml
Prevents nuking ecs-deploy-runner in default config
> don't nuke deploy runners

- aws/aws.go
Adds ACM resources to the resourcesInRegion list. 
Looks like this one slipped through the previous PR.
> add acm to resourcesInRegion

- aws/apigateway.go
- aws/apigateway_test.go
- aws/apigateway_types.go
- aws/aws.go
- aws/test_utils.go
- config/config.go
Making changes in code to have proper unit testing without calling AWS API - https://aws.amazon.com/blogs/developer/mocking-out-then-aws-sdk-for-go-for-unit-testing/. 
Currently, we call AWS API within unit tests and it causes several problems: 
* QuotaLimit
* Timeout
Also, I believe we can reduce the code inside `GetAllResources` function significantly with the new pattern of encapsulating "get resource" logic inside the ResourceType. Afterall, a better name for `ResourceType` would be just `Resource` but will make changes incrementally once this change looks good for everyone. 
Tackling issue: https://github.com/gruntwork-io/cloud-nuke/issues/494 …
> Mocking AWS Calls for Unit Testing for API Gateway

- aws/apigateway.go
- aws/apigateway_test.go
- aws/aws.go
- aws/kms_customer_key_test.go
- commands/cli.go
- config/config.go
- config/config_test.go
… prototype
Config improvement mentioned here: https://www.notion.so/gruntwork/Cloud-Nuke-Restructure-Proposal-845f291e952844ae8b0054ad0e466cfc. 
Tested running unit tests + locally running the cloud-nuke command
Updated [Refactor Config to Capture all FilterRules and Apply to ApiGateway as prototype]
> Refactor Config to Capture all FilterRules and Apply to ApiGateway as prototype

- aws/aws.go
- aws/eks.go
- aws/eks_test.go
- aws/eks_types.go
Tackling issue: https://github.com/gruntwork-io/cloud-nuke/issues/494
Updated [Refactor EksCluster ResourceType]
> Refactor EksCluster ResourceType

- aws/aws.go
- aws/rds_cluster.go
- aws/rds_cluster_test.go
- aws/rds_cluster_types.go
- config/config.go
- config/config_test.go
Tackling issue: https://github.com/gruntwork-io/cloud-nuke/issues/494
Updated [Refactor RDS Cluster ResourceType]
> Refactor RDS Cluster ResourceType

- aws/ami.go
- aws/ami_test.go
- aws/ami_types.go
- aws/aws.go
- commands/cli_test.go
Updated [Refactor AMI Resource Type]
> Refactor AMI Resource Type

- aws/asg.go
- aws/asg_test.go
- aws/asg_types.go
- aws/aws.go
Updated [Refactor auto scaling group resource type]
> Refactor auto scaling group resource type

- aws/aws.go
- aws/cloudtrail.go
- aws/cloudtrail_test.go
- aws/cloudtrail_types.go
Updated [Refactor cloudTrail resourceType]
> Refactor cloudTrail resourceType

- aws/aws.go
- aws/backup_vault.go
- aws/backup_vault_test.go
- aws/backup_vault_types.go
Updated [Refactor backupVault resourceType]
> Refactor backupVault resourceType

- aws/aws.go
- aws/cloudwatch_alarm.go
- aws/cloudwatch_alarm_test.go
- aws/cloudwatch_alarm_types.go
- aws/cloudwatch_dashboard.go
- aws/cloudwatch_dashboard_test.go
- aws/cloudwatch_dashboard_types.go
- aws/cloudwatch_loggroup.go
- aws/cloudwatch_loggroup_test.go
- aws/cloudwatch_loggroup_types.go
Updated [Refactor cloudwatch resource types]
> refactor cloudwatch resource types

- aws/aws.go
- aws/sqs.go
- aws/sqs_test.go
- aws/sqs_types.go
Updated [Refactor SQS Resource Type]
> Refactor SQS Resource Type

- aws/aws.go
- aws/secrets_manager.go
- aws/secrets_manager_test.go
- aws/secrets_manager_types.go
Updated [refactor secret manager resource type]
> refactor secret manager resource type

- aws/aws.go
- aws/rds_subnet_group.go
- aws/rds_subnet_group_test.go
- aws/rds_subnet_group_types.go
Updated [Refactor db subnet groups]
> Refactor db subnet groups

- aws/aws.go
- commands/cli.go
- config/config.go
ExcludeTimeAfter was not being set properly in configuration objects. 
This should fix the issue. 
Tested locally running the command using `--older-than` flag. 
Updated [Fix excludeTimeAfter configuration reflecting on all resource types]
> Fix excludeTimeAfter configuration reflecting on all resource types

- aws/aws.go
- aws/iam_group.go
- aws/iam_group_test.go
- aws/iam_group_types.go
> refactor IAM Groups

- aws/aws.go
- aws/iam_role.go
- aws/iam_role_test.go
- aws/iam_role_types.go
- aws/iam_service_linked_role.go
- aws/iam_service_linked_role_test.go
- aws/iam_service_linked_role_types.go
Updated [refactor IAM roles and IAM service linked roles]
> refactor IAM roles and IAM service linked roles

- aws/aws.go
- aws/kinesis_stream.go
- aws/kinesis_stream_test.go
- aws/kinesis_stream_types.go
Updated [refactor kinesis streams]
> refactor kinesis streams

- .circleci/nuke_config.yml
Fixes OIDC deletion exclude rule
Updated default nuke config
> fix oidc role exclusion

- aws/aws.go
- aws/eip.go
- aws/eip_test.go
- aws/eip_types.go
Updated [Refactor Eip]
Updated [refactor elastic cache]
> Refactor Eip

- aws/aws.go
- aws/ec2_key_pair.go
- aws/ec2_key_pair_test.go
- aws/ec2_key_pair_types.go
Updated [refactor EC2 keypair]
> refactor EC2 keypair

- aws/aws.go
- aws/s3.go
- aws/s3_test.go
- aws/s3_types.go
Updated [Refactor s3 resource type]
> Refactor s3 resource type

- aws/aws.go
- aws/kms_customer_key.go
- aws/kms_customer_key_test.go
- aws/kms_customer_key_types.go
Updated [refactor KMS resource type]
> refactor KMS resource type

- aws/resources/ami.go
- aws/resources/ami_test.go
partially fixes https://github.com/gruntwork-io/cloud-nuke/issues/563. 
Skipping AWS Managed AMIs when finding AMIs
Updated [Skipping AWS Managed AMIs when finding AMIs]
> Skip AWS Managed AMIs

- aws/resources/ecs_cluster.go
Fixes nil pointer issue
Updated [Fix nil pointer issue in ECS cluster resource type]
> Fix nil pointer issue in ECS cluster resource type

- aws/resources/s3.go
- config/config.go
- util/tag.go
Capability to include/exclude resource types based on tags
> Implement functionality to include/exclude resources by tags

- aws/resources/iam.go
- aws/resources/nat_gateway.go
- aws/resources/opensearch.go
- commands/cli.go
- logging/logger.go
Partially fix https://github.com/gruntwork-io/cloud-nuke/issues/552 issue about logging problem. 
Testing: verified debug level is set properly and working properly. 
Updated [Fix log-level not working properly]
> Fix log-level not working properly

- aws/aws.go
- aws/inspect.go
- aws/resources/kms_customer_key.go
- commands/cli.go
- config/config.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/572.
* Refactoring some common logic between `aws-nuke` and `aws-inspect` to have consistent logic & UI going forward
* made some changes to UI to make things cleaner. 
Here is the screenshot of the `aws-inspect` command: 
This is the screenshot when searching through aws resources
> UI improvement + refactoring work for aws-inspect and aws commands

- .circleci/nuke_config.yml
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/579. 
Testing
Without config files: 
With config file: 
> Inclusion Rule for ACM resource types in PhxDevops Account

- aws/resources/elasticache.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/486.
Testing: verified it doesn't retrieve default elasticcache group
> Filter out default subnet group due to error

- aws/aws.go
- aws/types.go
- aws/types_test.go
- commands/cli.go
- config/config.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/485. 
Testing with the newer-than filter (retrieve elements "newer" than 1 hour): 
Testing with the newer-than filter (retrieve elements "newer" than 1s):
TODO: we may want to reword these filters to `excludeAfter` and `includeAfter` to be consistent with the naming within the code. Also, it could be quite confusing to understand "older-than" and "newer-than". 
> Implement newer_than filter for aws nuke command

- aws/resources/cloudwatch_alarm.go
- aws/resources/cloudwatch_alarm_test.go
- util/string_utils.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/467. 
> Fix multiple cloudwatch composite alarm nuking

- README.md
Fixes #586 
Fix s3 config file key name in README
Updated documentation for the s3 resource type
> Fix s3 config file key name in README

- aws/resources/config_service.go
- aws/resources/config_service_test.go
Partially address https://github.com/gruntwork-io/cloud-nuke/issues/410. 
> Remove RemediationConfiguration before deleting config rules

- aws/resources/ec2_vpc.go
- aws/resources/ec2_vpc_test.go
- commands/cli.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/584. 
However, some VPC requires to run the cloud-nuke operations twice to delete completely. Some of the errors I couldn't resolve with this change: 
*   ERROR   Failed to nuke vpc with err: DependencyViolation: Network vpc-00db40ad268a8758a has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.
*   ERROR   Failed to nuke vpc with err: DependencyViolation: The subnet 'subnet-0ba8f9c12269ecc6c' has dependencies and cannot be deleted.
The first error goes away when I run it the second time. 
The second error seems to be legit error that subnet is being used in other instances. The caller would have to cleanup other resources (dependent) before nuking vpc. 
Read the [Gruntwork …
> Fix dependency violation errors when deleting EC2 VPC resource types

- .circleci/nuke_config.yml
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/579
> Exclude gruntwork.in ACM from nuking

- aws/resources/apigatewayv2.go
- aws/resources/apigatewayv2_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/594.
Successfully deleted all Api Gateway in phxdevops
> Remove associated Api mapping before deleting Api Gateway V2

- config/config.go
- config/config_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/579. 
Added unit tests to validate the expected behaviour. 
Also tested things locally. 
When we were reading config file + setting time filter together, we had a bug where the configuration file content would have been overwritten by time filter, instead of merging the two. 
> Fix the bug of overwriting config value generated from yml file

- .circleci/config.yml
- commands/cli.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/579. 
> Revert exclude-resource type for ACM + temporary log

- README.md
- aws/resource_registry.go
- aws/resources/ec2_dhcp_option.go
- aws/resources/ec2_dhcp_option_test.go
- aws/resources/ec2_dhcp_option_types.go
- config/config.go
- config/config_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/118. 
> Implement a new resource type for EC2 DHCP option

- aws/resources/ec2_dhcp_option.go
In a previous PR, forgot to add logic to report the result. 
Without this, we won't see final result. 
> Add report to ec2 DHCP option resource nuking operation

- aws/resource_registry.go
- aws/resources/rds_snapshot.go
- aws/resources/rds_snapshot_test.go
- aws/resources/rds_snapshot_types.go
- config/config.go
- config/config_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/120. 
> Implement a new resource type for RDS snapshot

- README.md
- aws/resources/ec2_key_pair.go
Fix some errors in README.
Also add one additional resource type, because I use it.
N/A, only extends new feature.
N/A
> Small improvements for exclude tags feature

- aws/resources/sqs.go
- aws/resources/sqs_test.go
This was broken by PR #517. SQS uses Unix timestamps, so we need to make sure to treat them as such.
Fixes #618.
- [N/A] Update the docs.
- [N/A] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [N/A] Include release notes. If this PR is backward incompatible, include a migration guide.
- [N/A] Attention Grunts - if this PR adds support for a new resource, ensure the `nuke_sandbox` and `nuke_phxdevops` jobs in `.circleci/config.yml` have been updated with appropriate exclusions (either …
> SQS: Fix timestamp parsing

- .circleci/nuke_config.yml
> Modify circleCi config to exclude test db subnet group

- aws/resource_registry.go
- aws/resources/transit_gateway.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/624.
> Implement wait logic in transite gateway attachment

- .circleci/config.yml
> Bump Cloud-nuke Circle Golang Version to 1.21

- README.md
- aws/resources/base_resource.go
- aws/resources/transit_gateway.go
- aws/resources/transit_gateway_test.go
- aws/resources/transit_gateway_types.go
- ui/ui.go
- util/error.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/361.
> Check for ownership when nuking transit gateway and show apprporiate error

- aws/resources/ecs_cluster.go
- aws/resources/ecs_cluster_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/368
> Stop tasks before nuking ECS cluster

- README.md
- aws/resource_registry.go
- aws/resources/elastic_beanstalk.go
- aws/resources/elastic_beanstalk_test.go
- aws/resources/elastic_beanstalk_types.go
- config/config.go
- config/config_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/351.
> elastic bean stalk application implementation

- aws/resources/apigateway.go
- aws/resources/apigateway_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/428
> api-gateway remove the attached client certs

- README.md
- aws/resource_registry.go
- aws/resources/route53_cidr_collection.go
- aws/resources/route53_cidr_collection_test.go
- aws/resources/route53_cidr_collection_types.go
- aws/resources/route53_hostedzone.go
- aws/resources/route53_hostedzone_test.go
- aws/resources/route53_hostedzone_types.go
- aws/resources/route53_traffic_policy.go
- aws/resources/route53_traffic_policy_test.go
- aws/resources/route53_traffic_policy_types.go
- config/config.go
- config/config_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/413
> support route53 services

- .circleci/nuke_config.yml
> Exclude gruntwork-test db parameter groups from nuking

- README.md
I've found it very annoying that the very top of the cloud-nuke README file is a note about telemetry. Being up front about this is important, but it shouldn't appear before the README even introduces what the tool is or does!
This PR moves the telemetry note below that, but still above install, so it should still get high visibility.
Fixes #000.
> Move telemetry down in README

- .circleci/nuke_config.yml
* Add name exclusion for IGW in phxdevops
Added name exclusion for IGW in phxdevops
> Add IGW exclusion to not delete in phxdevops

- README.md
- aws/resource_registry.go
- aws/resources/ec2_egress_only_igw.go
- aws/resources/ec2_egress_only_igw_test.go
- aws/resources/ec2_egress_only_igw_types.go
- config/config.go
- config/config_test.go
> Implement egress only internet gateway nuke

- README.md
- aws/resource_registry.go
- aws/resources/ec2_endpoints.go
- aws/resources/ec2_endpoints_test.go
- aws/resources/ec2_endpoints_types.go
- config/config.go
- config/config_test.go
> ec2 endpoint implementation in cloud-nuke

- .circleci/config.yml
* Adds `ec2-subnet` resource exclusion for `phxdevops`. We use default subnets for tests and they should not be deleted.
Added `ec2-subnet` resource exclusion for `phxdevops`
> Exclude ec2-subnet resource from phxdevops nuke config

- .circleci/config.yml
- aws/resources/s3.go
Fixes #659.
- As bucket versioning is managed separately and you can turn off versioning after the bucket is created, we need to check if there are any versions in the bucket regardless of the versioning status.
- Restore EIP deletion in PHXDevOps
> SME-256 S3 deletion

- aws/resources/s3_multi_region_access_point.go
- aws/resources/s3_multi_region_access_point_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/667.
> condition to allow multi region list only to us-west-2

- .circleci/nuke_config.yml
Updated patterns to remove S3 buckets created during Terragrunt tests
> Updated patterns to remove S3 buckets created in Terragrunt tests

- util/time.go
- util/time_test.go
Handle parsing of timestamps in time.DateTime format. Fixes #670
`cloud-nuke` (`v0.35.0`) is currently unable to parse EIPs (and possibly other resources) that are tagged with `cloud-nuke-first-seen` containing non-RFC3339 timestamp as you can see here:
This leads to the [EIP not being deleted](https://github.com/gruntwork-io/cloud-nuke/issues/670) due to the following error:
```
ERROR   Unable to retrieve eip, parsing time "2023-12-19 10:34:26" as "2006-01-02T15:04:05Z07:00": cannot parse " 10:34:26" as "T"
```
Fixed parsing of FirstSeenTag in non-RFC3339 format to fix EIP nuke
> Handle parsing of timestamps in time.DateTime format. Fix #670

- aws/aws.go
- aws/query.go
- aws/resources/ec2_subnet.go
- aws/resources/ec2_subnet_test.go
- aws/resources/ec2_vpc.go
- aws/resources/ec2_vpc_test.go
- aws/resources/security_group.go
- aws/resources/security_group_test.go
- aws/resources/security_group_types.go
- commands/cli.go
- config/config.go
- config/config_test.go
- util/error.go
Partially Fixing https://github.com/gruntwork-io/cloud-nuke/issues/651
TODO: make sure to use default on all EC2 resources. 
> Refactor nuking default resources code.

- .circleci/nuke_config.yml
Add a few patterns to clean up left over test resources.
> Add more Secrets Manager patterns

- README.md
- aws/resource_registry.go
- aws/resources/network_firewall.go
- aws/resources/network_firewall_policy.go
- aws/resources/network_firewall_policy_test.go
- aws/resources/network_firewall_policy_types.go
- aws/resources/network_firewall_rule_group.go
- aws/resources/network_firewall_rule_group_test.go
- aws/resources/network_firewall_rule_group_types.go
- aws/resources/network_firewall_test.go
- aws/resources/network_firewall_tls_config.go
- aws/resources/network_firewall_tls_config_test.go
- aws/resources/network_firewall_tls_config_types.go
- aws/resources/network_firewall_types.go
- config/config.go
- config/config_test.go
- util/error.go
- util/tag.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/684.
> Implementing nuking for Network Firewall resources

- README.md
- aws/resource_registry.go
- aws/resources/network_firewall_resource_policy.go
- aws/resources/network_firewall_resource_policy_test.go
- aws/resources/network_firewall_resource_policy_types.go
- config/config.go
- config/config_test.go
- util/error.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/684
> Nuke Network Resource Policy

- aws/resources/ec2_vpc.go
- aws/resources/ec2_vpc_test.go
- aws/resources/ec2_vpc_types.go
Fixes #https://github.com/gruntwork-io/cloud-nuke/issues/443.
> Implementation for removing VPC peer connection

- aws/resource_registry.go
- aws/resources/rds_cluster.go
- aws/resources/rds_global_cluster.go
- aws/resources/rds_global_cluster_membership.go
- aws/resources/rds_global_cluster_membership_test.go
- aws/resources/rds_global_cluster_membership_types.go
- aws/resources/rds_global_cluster_test.go
- aws/resources/rds_global_cluster_types_.go
- config/config.go
- config/config_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/597.
> Handle Global Cluster Nuke Failure

- .circleci/config.yml
- aws/resources/ec2_subnet_test.go
Following instruction here: https://circleci.com/docs/parallelism-faster-jobs/
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/697
Previously, all tests have been migrated to use mocking. 
We no longer have slow running tests so no need to run sequentially. 
> Increase parallelism for circleCi test

- aws/resources/ses_email_receiving.go
- aws/resources/ses_email_receiving_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/693.
> checking allowed regions for email-receiving

- README.md
- aws/resource_registry.go
- aws/resources/vpc_lattice_service.go
- aws/resources/vpc_lattice_service_network.go
- aws/resources/vpc_lattice_service_network_test.go
- aws/resources/vpc_lattice_service_network_types.go
- aws/resources/vpc_lattice_service_test.go
- aws/resources/vpc_lattice_service_type.go
- aws/resources/vpc_lattice_target_group.go
- aws/resources/vpc_lattice_target_group_test.go
- aws/resources/vpc_lattice_target_group_types.go
- config/config.go
- config/config_test.go
- util/error.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/701.
> implemented vpc lattice api

- telemetry/telemetry.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/703.
> issue panic without any command fix

- aws/resources/eip.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/675.
> fixed nil pointer issue on EIP resource

- README.md
Fixes #713.
Updated documentation for the `secretsmanager` resource type
n/a
> Fix secretsmanager config file key name in README

- aws/resource_registry.go
- aws/resources/route53_cidr_collection.go
- aws/resources/route53_hostedzone.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/705.
> Change Route53 resources to global resource

- aws/resources/route53_hostedzone.go
- aws/resources/route53_hostedzone_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/704.
> fix issue nuking route53

- .circleci/nuke_config.yml
Exclude specific Route53 zones from nuke-config.
> Exclude r53 zones

- README.md
- aws/resource_registry.go
- aws/resources/rds_proxy.go
- aws/resources/rds_proxy_test.go
- aws/resources/rds_proxy_types.go
- config/config.go
- config/config_test.go
> Implement nuking for RDS Proxy. 

- aws/resources/ec2_dhcp_option.go
- aws/resources/ec2_dhcp_option_test.go
- aws/resources/ec2_dhcp_option_types.go
Fixing DHCP nuke failing issues: 
```
Failed to delete DHCP option w/ err: DependencyViolation: The dhcpOptions 'dopt-286d8b41' has dependencies and cannot be deleted.
```
> Fixing dhcp nuke failing

- aws/resources/ses_email_receiving.go
- aws/resources/ses_email_receiving_test.go
> fix: active ruleset wont able to nuke

- README.md
- aws/resource_registry.go
- aws/resources/datasync_location.go
- aws/resources/datasync_location_test.go
- aws/resources/datasync_location_types.go
- aws/resources/datasync_task.go
- aws/resources/datasync_task_test.go
- aws/resources/datasync_task_types.go
- config/config.go
- config/config_test.go
Fixes #000.
add support for cleaning up [AWS DataSync](https://aws.amazon.com/datasync/) resources.
Added support for nuking `DataSync Task(s)` & `DataSync Location(s)`.
> add support for nuking dataSync Task(s) & dataSync Location(s).

- aws/resources/backup_vault.go
- aws/resources/backup_vault_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/730.
> fix: backup vault nuke failure with recovery point dependancy

- aws/resources/snapshot.go
- aws/resources/snapshot_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/727.
> Remove AMI created from the snapshot when nuking

- aws/resources/ec2_network_interface.go
- aws/resources/ec2_network_interface_test.go
- aws/resources/ec2_network_interface_types.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/731.
> Nuke only interface type ec2 network

- aws/resources/kms_customer_key.go
- aws/resources/lambda_layer.go
- aws/resources/security_hub.go
Noticed a couple of invalid checks:
```
aws/resources/kms_customer_key.go:64:10: impossible condition: nil != nil
aws/resources/lambda_layer.go:134:10: impossible condition: nil != nil
aws/resources/security_hub.go:108:9: tautological condition: nil == nil
```
Removed legacy code
> Legacy checks removal

- commands/cli.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/734.
> enabled exclude-first-seen flag for aws command

- aws/resources/cloudtrail.go
- util/error.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/752.
> Improve Failure Message for Insufficient Permission

- aws/resources/transit_gateway.go
- aws/resources/transit_gateway_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/744
> Fixing transit gateway nuke failure

- README.md
- aws/resource_registry.go
- aws/resources/ec2_placement_group.go
- aws/resources/ec2_placement_group_test.go
- aws/resources/ec2_placement_group_types.go
- config/config.go
- config/config_test.go
Support new resource type EC2 Placement groups
Added support for nuking EC2 Placement Groups.
> Support resource EC2 Placement Groups

- aws/resources/kms_customer_key.go
- aws/resources/sns.go
- config/config.go
- config/config_test.go
> fix: no name tag resources are listing for nuke with include filter

- aws/resources/route53_hostedzone.go
- aws/resources/route53_hostedzone_test.go
- aws/resources/route53_hostedzone_types.go
> fix: nuke failure when route53 record NS exists with subdomain

- aws/resources/config_service.go
- aws/resources/config_service_test.go
Nuking config rules fails if there is no remediation config. Add step to check existence of remediation configs before nuking.
```
┌─────────────────────────────────────────────────────────────────────────────────┐
| Resource Type    | Region         | Identifier                        | Nukable |
| ------------------------------------------------------------------------------- |
| config-rules     | ap-southeast-2 | encrypted-volumes                 | -       |
└─────────────────────────────────────────────────────────────────────────────────┘
WARNING  THE NEXT STEPS ARE DESTRUCTIVE AND COMPLETELY IRREVERSIBLE, PROCEED WITH CAUTION!!!
Are you sure you want to nuke all listed resources? Enter 'nuke' to confirm (or exit with ^C) : nuke
ERROR   Failed to delete remediation configuration w/ …
```
> Fix config rule nuking

- aws/resources/iam.go
- aws/resources/iam_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/763
> fix: iam user exclude not working

- aws/region.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/126
> feature: added support for china region

- README.md
- aws/resource_registry.go
- aws/resources/eventbridge_schedule.go
- aws/resources/eventbridge_schedule_group.go
- aws/resources/eventbridge_schedule_group_test.go
- aws/resources/eventbridge_schedule_group_types.go
- aws/resources/eventbridge_schedule_test.go
- aws/resources/eventbridge_schedule_types.go
- config/config.go
- config/config_test.go
- go.mod
- go.sum
Added support for [Amazon EventBridge Scheduler](https://docs.aws.amazon.com/eventbridge/latest/userguide/using-eventbridge-scheduler.html) - Schedules & Schedule group(s).
Added support for [Amazon EventBridge Scheduler](https://docs.aws.amazon.com/eventbridge/latest/userguide/using-eventbridge-scheduler.html) - Schedules & Schedule group(s).
n/a
> add support for eventBridge schedule & schedule groups.

- aws/resources/vpc_lattice_service.go
- aws/resources/vpc_lattice_service_network.go
- aws/resources/vpc_lattice_service_network_test.go
- aws/resources/vpc_lattice_service_network_types.go
- aws/resources/vpc_lattice_service_test.go
- aws/resources/vpc_lattice_service_type.go
- aws/resources/vpc_lattice_target_group.go
- aws/resources/vpc_lattice_target_group_types.go
- go.mod
- go.sum
- v2_migration_report/output.md
Partially fixing https://github.com/gruntwork-io/cloud-nuke/issues/770
> migrate: aws v2 - vpc lattice

- aws/resources/iam.go
- aws/resources/iam_group.go
- aws/resources/iam_group_test.go
- aws/resources/iam_group_types.go
- aws/resources/iam_policy.go
- aws/resources/iam_policy_test.go
- aws/resources/iam_policy_types.go
- aws/resources/iam_role.go
- aws/resources/iam_role_test.go
- aws/resources/iam_role_types.go
- aws/resources/iam_service_linked_role.go
- aws/resources/iam_service_linked_role_test.go
- aws/resources/iam_service_linked_role_types.go
- aws/resources/iam_test.go
- aws/resources/iam_types.go
- go.mod
- go.sum
- util/tag.go
- v2_migration_report/output.md
change port resources to aws SDK v2
- iam
- iam-group
- iam-policy
- iam-role
- iam-service-linked-role
n/a
> change port iam, iam-group, iam-policy, iam-role, iam-service-linked-role to awsSDKv2

- .circleci/config.yml
Fixes CI issue where all regions aren't being flushed.
Updated the CI to flush all regions.
> fix: Adding all regions to cloud nuke invocation

- aws/resources/elasticache.go
running nuke on single node elasticache cluster fails with `address or nil pointer dereference`
Fixes #782
[x] Fixes #782 single node elasticache cluster fails with `address or nil pointer dereference`
n/a
> fix #782 elasticache crash on `address or nil pointer dereference` in case we have a single node cluster.

- aws/resources/snapshot.go
- aws/resources/snapshot_test.go
- aws/resources/snapshot_types.go
- v2_migration_report/output.md
Fixes #770.
Updated `snapshot` to AWS SDK v2
> Migrate Snapshot to AWS SDK v2

- aws/resources/opensearch.go
- aws/resources/opensearch_test.go
- aws/resources/opensearch_types.go
- go.mod
- go.sum
- v2_migration_report/output.md
Fixes #770.
Updated `opensearchservice` to AWS SDK v2
> Migrate OpenSearch to AWS SDK v2

- README.md
- config/examples/complete.yaml
- config/examples/simple.yaml
fixes https://github.com/gruntwork-io/cloud-nuke/issues/786.
> add config example

- aws/resources/ec2_egress_only_igw.go
- aws/resources/ec2_egress_only_igw_test.go
- aws/resources/ec2_egress_only_igw_types.go
- aws/resources/ec2_endpoints.go
- aws/resources/ec2_internet_gateway.go
- aws/resources/ec2_internet_gateway_test.go
- aws/resources/ec2_internet_gateway_types.go
- aws/resources/ec2_network_acl.go
- aws/resources/ec2_network_acl_test.go
- aws/resources/ec2_network_acl_types.go
- aws/resources/ec2_network_interface.go
- aws/resources/ec2_network_interface_test.go
- aws/resources/ec2_network_interface_types.go
- aws/resources/ec2_subnet.go
- aws/resources/ec2_subnet_test.go
- aws/resources/ec2_subnet_types.go
- aws/resources/ec2_vpc.go
- aws/resources/ec2_vpc_test.go
- aws/resources/ec2_vpc_types.go
- aws/resources/nat_gateway.go
- aws/resources/nat_gateway_test.go
- aws/resources/nat_gateway_types.go
- aws/resources/security_group.go
- aws/resources/security_group_test.go
- aws/resources/security_group_types.go
- util/error.go
- util/time.go
- v2_migration_report/output.md
> Migrate to AWS SDK v2 for vpc and dependant services

- aws/resources/tgw_route_tables.go
- aws/resources/tgw_route_tables_test.go
- aws/resources/tgw_route_tables_types.go
- v2_migration_report/output.md
Fixes #770. These commits are cherry-picked from my other PR here: https://github.com/gruntwork-io/cloud-nuke/pull/800
Updated `transit-gateway-route-table` to AWS SDK v2
> Migrate TGW Route Table to AWS SDK v2

- aws/resources/redshift.go
- aws/resources/redshift_test.go
- aws/resources/redshift_types.go
- go.mod
- go.sum
- v2_migration_report/output.md
> Migrate to AWS SDK v2 for route53,redshift modules

- aws/resources/ec2.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/805
> Add nil pointer checks to avoid exception for VPC nuke

- README.md
- aws/resources/ec2_vpc.go
- aws/resources/ec2_vpc_test.go
Fixes #810 add support `cloud-nuke-excluded` tag.
Added support `cloud-nuke-excluded` tag - Fixes #810 
n/a
> add support for `cloud-nuke-excluded` tag in VPC resource, fix #810

- util/error_test.go
This change adds test coverage for the `TransformAWSError` function to ensure all cases are covered during the AWS SDK v2 migration.
Added tests for `TransformAWSError` func from `util` pkg before migrating to aws SDK v2
n/a
> add tests for `TransformAWSError` func from `util` pkg before migrating to aws SDK v2.

- aws/resources/route53_hostedzone.go
Add pagination support for Route53HostedZones resource to list and delete all existing resources. Currently, the list operation did only a single request so it was only able to delete 100 HostedZones/Records (default max number of the element returned by the `ListHostedZone` / `ListResourceRecordSets` API calls.
Ref: https://github.com/aws/aws-sdk-go-v2/blob/service/route53/v1.46.3/service/route53/api_op_ListHostedZones.go#L38-L63
Fixes #817.
Add Route53HostedZones pagination support to list & delete all hosted zones  [X].
> Ensure all Route53HostedZones are deleted by adding pagination support

- aws/resources/ec2_vpc.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/818.
> Decrease the timeout period for network interface nuking operation

- .circleci/config.yml
We're encountering issues following the recent migration in cloud-nuke, which may be resolved by upgrading the Go version. For more details, refer to: https://go.dev/blog/loopvar-preview.
> Increase go_version to 1.22.6

- aws/resources/transit_gateway_types.go
Fixes #825 Attempting to assign to a nil map in the transit gateway
before the patch
```sh
$ go run main.go aws --region eu-west-1 --resource-type transit-gateway
┌───────────────────────────────────────────┐
| Query Parameter         | Value           |
| ----------------------------------------- |
| Target Regions          | eu-west-1       |
| Target Resource Types   | transit-gateway |
| List Unaliased KMS Keys | false           |
└───────────────────────────────────────────┘
▀  Searching transit-gateway resources in eu-west-1 (1s)ERRO[2025-01-13T18:32:05Z] assignment to entry in nil map                binary=cloud-nuke version=
exit status 1
```
after the patch
```sh
$ go run main.go aws --region eu-west-1 --resource-type transit-gateway
┌───────────────────────────────────────────┐ …
```
> fix for #825 assignment to nil map in TG.

- aws/resources/macie.go
- logging/logger.go
Seeing nil pointer exception when nuking macie resources. 
```
Nuking batch of 1 macie-member resource(s) in ap-south-1 [4/2373]  0% | 6sERRO[2025-02-17T04:29:24Z] runtime error: invalid memory address or nil pointer dereference  binary=cloud-nuke version=63bbc48e814cec0bfd467b12cc1efb4b20219801
```
> Fix nil pointer exception for macie nukeAll operation

- .circleci/config.yml
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/836.
> Delete excluding config-recorders from nuking operation

- .circleci/config.yml
Fixes #841. Adds cloud-nuke support for a new AWS account, CONFIGTESTS. 
Adds cloud-nuke support for a new AWS account CONFIGTESTS
> enable cloud-nuke for new AWS account CONFIGTESTS

- .circleci/config.yml
Updates the container image used for the CONFIGTESTS account. Missed this in a previous PR so this will resolve job failures due to using the wrong image. 
Updated container image being used by configtests job
> update configtests image

- aws/region.go
- aws/region_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/832
> allow global region to be overriden by env

- aws/resources/rds_subnet_group.go
- aws/resources/rds_subnet_group_test.go
- aws/resources/rds_subnet_group_types.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/848.
> Support proper tag reading in RDS module

- README.md
- aws/resource_registry.go
- aws/resources/sagemaker_endpoint.go
- aws/resources/sagemaker_endpoint_test.go
- aws/resources/sagemaker_endpoint_types.go
- config/config.go
- config/examples/complete.yaml
- util/tag.go
Added support for SageMaker Endpoint deletion with ability to filter by name, creation date and tags.
- Added support for SageMaker Endpoint.
No breaking changes.
> Added new resource - SageMaker Endpoint

- .circleci/config.yml
Start nuking global resources. Excluding other global resources other than iam-instance-profiles to be safe that it doesn't affect other parts of the system unintentionally. 
As part of this linear ticket: https://linear.app/gruntwork/issue/SME-2887/iamlimitexceeded-cannot-exceed-quota-for-instanceprofilesperaccount
> Start nuking global resources as part of circleCi automated nuking operation

- README.md
- aws/resource_registry.go
- aws/resources/sagemaker_endpoint_config.go
- aws/resources/sagemaker_endpoint_config_test.go
- aws/resources/sagemaker_endpoint_config_types.go
- config/config.go
- config/examples/complete.yaml
Added support for SageMaker Endpoint configuration deletion with ability to filter by name, creation date and tags.
- Added support for SageMaker Endpoint.configuration
No breaking changes.
> Add new resource - SageMaker Endpoint configuration

- aws/resources/eks.go
- aws/resources/eks_test.go
Fixes https://github.com/gruntwork-io/cloud-nuke/issues/862.
> fix name regex for EKS cluster 

- .circleci/config.yml
Had originally issue with this PR - https://github.com/gruntwork-io/cloud-nuke/commit/98fb5dae4bc9cf37ca4c45ace5cb35fd306a681d. 
Turns out there were some spaces in the command line. 
> Start nuking global resources to cleanup some left-over resources in test environment. 

- .circleci/config.yml
Noticed that cloud-nuke was deleting the internet-gateway for default VPCs in the configtests account (used by terraform-aws-security), which broke some tests. Would like to exclude this so we retain internet-gateways for default VPCs.
Please let me know if there is a better way to handle this! 
Updated CircleCi config to exclude internet-gateway deletion for configtests account
> exclude internet-gateway for configtests

- aws/resources/iam_role.go
- aws/resources/iam_role_test.go
Fixes #https://github.com/gruntwork-io/cloud-nuke/issues/880.
> Update IAMRoles.shouldInclude to filter out AWS-managed service linked roles

- README.md
- aws/resources/iam_role.go
- aws/resources/iam_role_test.go
- aws/resources/iam_role_types.go
Fixes #889.
Added tag filtering support for IAM roles
<sub>Jan Roehrich <jan.roehrich@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>
> feat(iam-role): add tag filtering support

- config/config.go
- config/config_tag_test.go
Fixes #886 - Resources without tags are now correctly excluded when tag inclusion filters are specified.
- Modified `ShouldIncludeBasedOnTag` to properly handle untagged resources when inclusion rules exist
- Added comprehensive unit tests for tag filtering behavior
Added test cases covering all tag filtering scenarios including untagged resources with inclusion/exclusion rules.
> fix: tag inclusion filtering to properly exclude untagged resources

- aws/resources/network_firewall_resource_policy.go
- Fixed nil pointer dereference error when running `cloud-nuke inspect-aws --resource-type network-firewall-resource-policy`
- Added proper nil check for the output from DescribeResourcePolicy API call before accessing its fields
When querying network firewall resource policies, the code was experiencing a runtime panic with "invalid memory address or nil pointer dereference" error. This occurred because the DescribeResourcePolicy API can return a nil output even when no error is returned, and the code was attempting to access `output.Policy` without first checking if `output` itself was nil.
> fix: handle nil output from DescribeResourcePolicy in network firewall
